// Presets: answer one question instead of twelve.
// Each preset is a complete config (minus name/pm/git/install which are always asked).

export const ESSENTIAL_COMPONENTS_LIST = ["button", "card", "input", "badge"];

export const PRESETS = {
  minimal: {
    label: "Minimal",
    hint: "Vite + TS + Tailwind + shadcn + TanStack Router — nothing else",
    config: {
      backend: "none",
      orm: "none",
      dbProvider: "none",
      auth: "none",
      router: "tanstack",
      ai: "none",
      state: "none",
      components: ["label"],
      extras: ["prettier"],
    },
  },
  saas: {
    label: "SaaS",
    hint: "Convex + Clerk + Stripe + Resend + PostHog + Sentry + tests + CI",
    config: {
      backend: "convex",
      orm: "none",
      dbProvider: "none",
      auth: "clerk",
      router: "tanstack",
      ai: "none",
      state: "zustand",
      components: ["label", "dialog", "sonner", "dropdown-menu", "avatar", "tabs", "table", "skeleton"],
      extras: [
        "query",
        "table",
        "forms",
        "charts",
        "stripe",
        "resend",
        "posthog",
        "sentry",
        "testing",
        "e2e",
        "prettier",
        "husky",
        "ci",
        "deploy",
        "fallow",
      ],
    },
  },
  fullstack: {
    label: "Full-stack API",
    hint: "Hono + tRPC + Drizzle + Neon + Clerk + Biome + tests + CI",
    config: {
      backend: "hono",
      orm: "drizzle",
      dbProvider: "neon",
      auth: "clerk",
      router: "tanstack",
      ai: "none",
      state: "zustand",
      linter: "biome",
      components: ["label", "dialog", "sonner", "table"],
      extras: ["forms", "table", "testing", "husky", "ci", "deploy", "fallow"],
    },
  },
  ai: {
    label: "AI app",
    hint: "Convex + Clerk + AI SDK (Claude) streaming chat",
    config: {
      backend: "convex",
      orm: "none",
      dbProvider: "none",
      auth: "clerk",
      router: "tanstack",
      ai: "anthropic",
      state: "none",
      components: ["label", "dialog", "sonner", "skeleton", "textarea"],
      extras: ["query", "testing", "prettier", "ci"],
    },
  },
  everything: {
    label: "Everything",
    hint: "Every feature and every extra — the kitchen sink",
    config: {
      backend: "convex",
      orm: "none",
      dbProvider: "none",
      auth: "clerk",
      router: "tanstack",
      ai: "anthropic",
      state: "zustand",
      components: [
        "label",
        "dialog",
        "dropdown-menu",
        "sonner",
        "tabs",
        "avatar",
        "skeleton",
        "select",
        "checkbox",
        "switch",
        "textarea",
        "tooltip",
        "separator",
        "table",
      ],
      // extras filled in dynamically with ALL_EXTRAS by the caller
      extras: "all",
    },
  },
  custom: {
    label: "Custom",
    hint: "choose every option yourself",
    config: null,
  },
};

export const PRESET_NAMES = Object.keys(PRESETS);
